[workspace]
members = [
    "tardis",
    "libtardis",
    "loader",
]

[workspace.dependencies]
deku = "0.14.1"
lz4_flex = { version = "0.9.2", default-features = false, features = ["safe-encode", "safe-decode"] }

[profile.release]
strip = "symbols"
lto = true
opt-level = "s"
